"""Rebuildable support-edge cache for fast provenance walks.

The cache denormalises every ``supports_json`` entry into a row of
``(claim_id, supports_claim_id, position)`` so recursive CTEs can walk
the dependency graph without re-parsing JSON arrays on every step.

It lives in a *separate* SQLite file at
``.mareforma/claim_supports_cache.db`` rather than as a new column or
side-table inside ``graph.db``. The cache is *not* part of the signed-
graph integrity surface: it is fully rederivable from
``claims.supports_json`` and is rebuilt transparently whenever a
mismatch is detected. Keeping it outside the versioned schema means
the file can be deleted with no consequences beyond a one-time rebuild
on next open.

Cache layout::

    ATTACH DATABASE '<root>/.mareforma/claim_supports_cache.db' AS supports_cache
    supports_cache.claim_supports(
        claim_id          TEXT NOT NULL,
        supports_claim_id TEXT NOT NULL,
        position          INTEGER NOT NULL,
        PRIMARY KEY (claim_id, supports_claim_id)
    )
    supports_cache.idx_supports_reverse ON (supports_claim_id, claim_id)
    supports_cache.cache_meta(key TEXT PRIMARY KEY, value TEXT)

The reverse index serves "what claims support X?" queries by walking
``supports_claim_id → claim_id`` in O(deg(X)).

Maintenance contract:

* :func:`attach_cache` is called once per opened connection by the
  graph-open path.
* :func:`record_supports_edges` is called inside
  :func:`mareforma.db.add_claim`'s ``BEGIN IMMEDIATE`` so the edge
  rows and the main-claim INSERT commit together on the normal path.
  This is best effort, not an atomicity guarantee: the cache is an
  attached database and both databases run WAL, and SQLite commits an
  attached WAL database per database rather than as a set, so a crash
  between the two commits can leave one written and the other not.
* :func:`rebuild_cache` is called when :func:`is_cache_stale` returns
  True at attach time (cache file missing, count mismatch with the
  main graph, etc.) and at the tail of :func:`mareforma.db.restore`
  after the full chain has been replayed. Every edge write bumps
  ``supports_revision`` in graph.db and stamps the new value on the
  cache, so a torn commit leaves the two apart and the next attach
  rebuilds. That covers the in-place supports edit, which moves no
  claim count and is invisible to the count check.

Only UUID-shaped supports refs (the strict v4 form generated by
``uuid.uuid4()``) are cached. DOI, arXiv, and free-text refs in
``supports[]`` are *external*: they have no ``urn:mareforma:claim:``
identity inside the local graph and would never satisfy a recursive
walk. Filtering them at cache-write time keeps reverse-index lookups
clean.
"""

from __future__ import annotations

import re
import sqlite3
from pathlib import Path


__all__ = [
    "CACHE_FILENAME",
    "attach_cache",
    "record_supports_edges",
    "is_cache_stale",
    "rebuild_cache",
    "supports_revision",
    "set_supports_revision",
    "walk_upstream",
    "walk_downstream",
    "claim_supports_count",
]


CACHE_FILENAME = "claim_supports_cache.db"

# Strict UUIDv4, version nibble == 4, variant nibble in {8,9,a,b}.
# Matches mareforma.db._is_claim_id; duplicated here to keep this
# module a leaf with no circular import on db.
_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)


# WAL on both DBs so a writer holding the graph.db lock isn't blocked by
# cache readers. WAL buys concurrency only: it does not extend the
# main-graph transaction over the attached cache, since SQLite commits
# attached WAL databases one at a time rather than under one
# super-journal.
_CACHE_SCHEMA = """
PRAGMA supports_cache.journal_mode=WAL;

CREATE TABLE IF NOT EXISTS supports_cache.claim_supports (
    claim_id          TEXT NOT NULL,
    supports_claim_id TEXT NOT NULL,
    position          INTEGER NOT NULL,
    PRIMARY KEY (claim_id, supports_claim_id)
);

CREATE INDEX IF NOT EXISTS supports_cache.idx_supports_reverse
    ON claim_supports (supports_claim_id, claim_id);

CREATE TABLE IF NOT EXISTS supports_cache.cache_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
"""


# The cache is unsigned and rebuildable, so a walk may only narrow what
# the signed rows already say. Every edge it returns must still be cited
# by the parent's authoritative claims.supports_json; a planted or
# half-written cache row names an ancestry no signature covers. Applied
# to both arms of both walks, the same re-check the convergence
# candidate lookup runs before a promotion.
_EDGE_IS_ATTESTED = """
            AND EXISTS (
                SELECT 1 FROM claims c, json_each(c.supports_json) e
                 WHERE c.claim_id = cs.claim_id
                   AND e.value = cs.supports_claim_id
            )"""


def _cache_path(root: Path) -> Path:
    return root / ".mareforma" / CACHE_FILENAME


def attach_cache(conn: sqlite3.Connection, root: Path) -> None:
    """Attach the cache DB to *conn* and ensure schema + freshness.

    Idempotent: re-calling on an already-attached connection is a
    no-op (the ATTACH itself raises an OperationalError which we
    silently treat as already-attached).

    Concurrent first-open contention: if two processes open the
    project simultaneously on a missing or stale cache, both will
    race for the ``BEGIN IMMEDIATE`` inside :func:`rebuild_cache`.
    The loser receives ``SQLITE_BUSY`` after the connection's
    ``busy_timeout`` expires. We set a 5-second timeout here so the
    losing process waits for the rebuild to finish instead of
    failing the open call.
    """
    path = _cache_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        conn.execute("ATTACH DATABASE ? AS supports_cache", (str(path),))
    # sqlite3.DatabaseError covers both OperationalError and the
    # bare-form DatabaseError that ATTACH raises on a non-SQLite file
    # ("file is not a database"). Catching the parent class lets a
    # single handler recover from "already attached" / "corrupt file".
    except sqlite3.Error as exc:
        msg = str(exc).lower()
        # Already attached → benign no-op.
        if "already" in msg:
            return
        # Corrupt cache file → unlink + retry ATTACH once. The cache is
        # explicitly rebuildable from claims.supports_json and the
        # alternative ("delete this file manually") is operator-toil
        # we don't need to inflict for a non-signed cache.
        corruption_markers = (
            "not a database", "malformed", "corrupt", "file is encrypted",
        )
        if path.exists() and any(m in msg for m in corruption_markers):
            import warnings as _warnings
            _warnings.warn(
                f"claim_supports cache file at {path} appears corrupt "
                f"({exc}); unlinking and rebuilding.",
                RuntimeWarning,
                stacklevel=2,
            )
            try:
                path.unlink()
            except OSError:
                pass
            conn.execute("ATTACH DATABASE ? AS supports_cache", (str(path),))
            # Fall through to schema + rebuild below.
        else:
            raise
    # Wait up to 5s on a contended write lock so two concurrent
    # first-opens don't fail one of them with SQLITE_BUSY mid-rebuild.
    conn.execute("PRAGMA busy_timeout = 5000")
    conn.executescript(_CACHE_SCHEMA)
    if is_cache_stale(conn):
        rebuild_cache(conn)


def is_cache_stale(conn: sqlite3.Connection) -> bool:
    """Freshness check: claim count and supports revision vs the main graph.

    Compares the number of distinct ``claim_id`` rows in the cache to
    the count stamped at the last full rebuild, then the stamped
    ``supports_revision`` to the counter graph.db carries. Either
    mismatch ⇒ cache lost writes (an external process wrote to
    graph.db with a mareforma version that did not maintain the cache,
    or a crash committed one database and not the other).

    The revision is what catches an in-place supports edit: that write
    moves no claim count, so the count check alone would serve the
    pre-edit lineage forever.

    A missing ``cache_meta`` row means the cache has never been
    populated and a rebuild is required.
    """
    stamped_count = _stamped_meta(conn, "source_claim_count")
    if stamped_count is None:
        return True
    current = conn.execute(
        "SELECT COUNT(*) AS n FROM claims"
    ).fetchone()["n"]
    if stamped_count != current:
        return True
    stamped_revision = _stamped_meta(conn, "source_revision")
    if stamped_revision is None:
        return True
    return stamped_revision != supports_revision(conn)


def _stamped_meta(conn: sqlite3.Connection, key: str) -> int | None:
    """Read an integer ``cache_meta`` value, or None when absent/unparseable."""
    row = conn.execute(
        "SELECT value FROM supports_cache.cache_meta WHERE key = ?", (key,),
    ).fetchone()
    if row is None:
        return None
    try:
        return int(row["value"])
    except (TypeError, ValueError):
        return None


def supports_revision(conn: sqlite3.Connection) -> int:
    """Return graph.db's supports-edge revision counter.

    The counter lives in the main graph, so it commits with the claims row
    whose edges it describes. The cache stamps the value it observed at every
    edge write; :func:`is_cache_stale` compares the two.
    """
    row = conn.execute(
        "SELECT revision FROM supports_revision WHERE id = 1"
    ).fetchone()
    return 0 if row is None else int(row["revision"])


def set_supports_revision(conn: sqlite3.Connection, revision: int) -> None:
    """Set the counter, used by restore to resume a backed-up graph's value.

    Restoring at 0 would let the counter climb back through values a
    surviving cache file already stamped, so a cache holding pre-loss edges
    could read as fresh.
    """
    conn.execute(
        "INSERT INTO supports_revision (id, revision) VALUES (1, ?) "
        "ON CONFLICT(id) DO UPDATE SET revision = excluded.revision",
        (int(revision),),
    )


def _bump_supports_revision(conn: sqlite3.Connection) -> None:
    """Advance the graph-side counter and stamp the new value on the cache.

    Called by every mutator that writes cache edges, inside the caller's
    transaction. A crash that commits graph.db without the attached cache
    leaves the stamp behind the counter, which is what
    :func:`is_cache_stale` reads on the next open.
    """
    conn.execute(
        "INSERT INTO supports_revision (id, revision) VALUES (1, 1) "
        "ON CONFLICT(id) DO UPDATE SET revision = revision + 1"
    )
    conn.execute(
        "INSERT OR REPLACE INTO supports_cache.cache_meta (key, value) "
        "VALUES ('source_revision', ?)",
        (str(supports_revision(conn)),),
    )


def rebuild_cache(conn: sqlite3.Connection) -> int:
    """Wipe the cache and re-derive every edge from ``claims.supports_json``.

    Returns the number of edge rows written. Called by
    :func:`attach_cache` when the cache is stale and at the tail of
    :func:`mareforma.db.restore` once the full chain has replayed.

    Runs inside its own transaction so the wipe-and-refill is atomic
    even if the main graph's transaction has not yet opened.
    """
    import json

    conn.execute("BEGIN IMMEDIATE")
    try:
        conn.execute("DELETE FROM supports_cache.claim_supports")
        rows = conn.execute(
            "SELECT claim_id, supports_json FROM claims"
        ).fetchall()
        written = 0
        for row in rows:
            try:
                refs = json.loads(row["supports_json"] or "[]")
            except (json.JSONDecodeError, TypeError):
                continue
            if not isinstance(refs, list):
                continue
            for position, ref in enumerate(refs):
                if isinstance(ref, str) and _UUID_RE.match(ref):
                    conn.execute(
                        "INSERT OR IGNORE INTO supports_cache.claim_supports "
                        "(claim_id, supports_claim_id, position) "
                        "VALUES (?, ?, ?)",
                        (row["claim_id"], ref, position),
                    )
                    written += 1
        total = conn.execute(
            "SELECT COUNT(*) AS n FROM claims"
        ).fetchone()["n"]
        conn.execute(
            "INSERT OR REPLACE INTO supports_cache.cache_meta "
            "(key, value) VALUES ('source_claim_count', ?)",
            (str(total),),
        )
        conn.execute(
            "INSERT OR REPLACE INTO supports_cache.cache_meta "
            "(key, value) VALUES ('source_revision', ?)",
            (str(supports_revision(conn)),),
        )
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    return written


def record_supports_edges(
    conn: sqlite3.Connection,
    claim_id: str,
    supports: list[str] | None,
) -> None:
    """Append edges for a newly-asserted claim.

    Called by :func:`mareforma.db.add_claim` *inside* its
    ``BEGIN IMMEDIATE`` transaction so the cache rows commit together
    with the main-claim INSERT. Filters non-UUID refs so the cache
    stays clean of external (DOI / arXiv / free-text) identifiers.

    Also bumps ``cache_meta.source_claim_count`` by 1 and the graph's
    ``supports_revision`` to keep the staleness witnesses in sync;
    restoring or external tampering still triggers a full rebuild via
    :func:`is_cache_stale`.
    """
    if not supports:
        # Still bump the count, every claim INSERT changes the source
        # claim count, regardless of whether it has UUID-shaped refs.
        _bump_source_count(conn, delta=1)
        _bump_supports_revision(conn)
        return
    for position, ref in enumerate(supports):
        if isinstance(ref, str) and _UUID_RE.match(ref):
            conn.execute(
                "INSERT OR IGNORE INTO supports_cache.claim_supports "
                "(claim_id, supports_claim_id, position) "
                "VALUES (?, ?, ?)",
                (claim_id, ref, position),
            )
    _bump_source_count(conn, delta=1)
    _bump_supports_revision(conn)


def replace_supports_edges(
    conn: sqlite3.Connection,
    claim_id: str,
    supports: list[str] | None,
) -> None:
    """Re-derive a claim's edges after its ``supports_json`` was edited.

    Called by :func:`mareforma.db.update_claim` *inside* its transaction when
    an unsigned claim's supports change. Drops the claim's existing edges and
    re-inserts from the new list, filtering non-UUID refs like
    :func:`record_supports_edges`. Does NOT touch
    ``cache_meta.source_claim_count``: an in-place edit changes no claim count,
    and the count witness must not be nudged out of step. It does bump
    ``supports_revision``, which is the witness that sees this write: a crash
    that loses the cache half of the edit then leaves the stamp behind the
    graph and the next open rebuilds.
    """
    conn.execute(
        "DELETE FROM supports_cache.claim_supports WHERE claim_id = ?",
        (claim_id,),
    )
    for position, ref in enumerate(supports or []):
        if isinstance(ref, str) and _UUID_RE.match(ref):
            conn.execute(
                "INSERT OR IGNORE INTO supports_cache.claim_supports "
                "(claim_id, supports_claim_id, position) "
                "VALUES (?, ?, ?)",
                (claim_id, ref, position),
            )
    _bump_supports_revision(conn)


def remove_claim_edges(
    conn: sqlite3.Connection,
    claim_id: str,
    *,
    count_delta: int = -1,
) -> None:
    """Drop a deleted claim's edges in both directions.

    Called by :func:`mareforma.db.delete_claim` *inside* its transaction. A
    delete leaves edges pointing to and from the row; remove both so downstream
    and upstream walks stop surfacing the dangling claim. ``count_delta``
    decrements ``source_claim_count`` by the number of claims removed so the
    staleness counter stays in step with the claim count.
    """
    conn.execute(
        "DELETE FROM supports_cache.claim_supports "
        "WHERE claim_id = ? OR supports_claim_id = ?",
        (claim_id, claim_id),
    )
    if count_delta:
        _bump_source_count(conn, delta=count_delta)
    _bump_supports_revision(conn)


def _bump_source_count(conn: sqlite3.Connection, *, delta: int) -> None:
    """Increment the staleness counter (creating the row if absent)."""
    row = conn.execute(
        "SELECT value FROM supports_cache.cache_meta "
        "WHERE key = 'source_claim_count'"
    ).fetchone()
    if row is None:
        # Cache was just initialised mid-write. Stamp the current
        # claim count (which already includes the row we just inserted
        # because we're inside its transaction).
        current = conn.execute(
            "SELECT COUNT(*) AS n FROM claims"
        ).fetchone()["n"]
        conn.execute(
            "INSERT OR REPLACE INTO supports_cache.cache_meta "
            "(key, value) VALUES ('source_claim_count', ?)",
            (str(current),),
        )
        return
    try:
        current = int(row["value"]) + delta
    except (TypeError, ValueError):
        current = conn.execute(
            "SELECT COUNT(*) AS n FROM claims"
        ).fetchone()["n"]
    conn.execute(
        "UPDATE supports_cache.cache_meta SET value = ? WHERE key = "
        "'source_claim_count'",
        (str(current),),
    )


def claim_supports_count(conn: sqlite3.Connection) -> int:
    """Return total edge rows in the cache. Test / health surface."""
    return conn.execute(
        "SELECT COUNT(*) AS n FROM supports_cache.claim_supports"
    ).fetchone()["n"]


def walk_upstream(
    conn: sqlite3.Connection,
    claim_id: str,
    *,
    depth: int = 4,
) -> list[dict]:
    """Recursive CTE walk: claim_id → supports_claim_id → ... .

    Returns a list of ``{claim_id, depth, position}`` rows. ``depth=1``
    is the direct supports of *claim_id*; ``depth=N`` includes
    everything up to N hops. ``depth=0`` returns the seed only.

    Depth is bounded to keep pathological cycles from looping forever
    even though :func:`mareforma.db.add_claim` rejects self-loops at
    write time. Default 4 matches :meth:`EpistemicGraph.query_provenance`:
    deep enough for most provenance audits without dragging the
    entire ancestral chain on every call.

    Every hop is re-checked against the parent's signed
    ``claims.supports_json``, so a cache edge nothing attests is
    dropped rather than reported as lineage.
    """
    if depth < 1:
        return []
    rows = conn.execute(
        f"""
        WITH RECURSIVE upstream(claim_id, supports_claim_id, depth, position)
        AS (
            SELECT cs.claim_id, cs.supports_claim_id, 1 AS depth, cs.position
              FROM supports_cache.claim_supports cs
             WHERE cs.claim_id = ?{_EDGE_IS_ATTESTED}
            UNION ALL
            SELECT cs.claim_id, cs.supports_claim_id, u.depth + 1, cs.position
              FROM supports_cache.claim_supports cs
              JOIN upstream u ON cs.claim_id = u.supports_claim_id
             WHERE u.depth < ?{_EDGE_IS_ATTESTED}
        )
        SELECT DISTINCT supports_claim_id AS claim_id, depth, position
          FROM upstream
         ORDER BY depth, position, supports_claim_id
        """,
        (claim_id, depth),
    ).fetchall()
    return [dict(r) for r in rows]


def walk_downstream(
    conn: sqlite3.Connection,
    claim_id: str,
    *,
    depth: int = 4,
) -> list[dict]:
    """Reverse walk: what claims (transitively) support *claim_id*?

    Uses the ``idx_supports_reverse`` index for O(deg) per hop. Returns
    ``{claim_id, depth, position}`` rows where ``claim_id`` is a
    downstream consumer. Edges are re-checked against the citing
    claim's signed ``claims.supports_json``, as in :func:`walk_upstream`.
    """
    if depth < 1:
        return []
    rows = conn.execute(
        f"""
        WITH RECURSIVE downstream(claim_id, supports_claim_id, depth, position)
        AS (
            SELECT cs.claim_id, cs.supports_claim_id, 1 AS depth, cs.position
              FROM supports_cache.claim_supports cs
             WHERE cs.supports_claim_id = ?{_EDGE_IS_ATTESTED}
            UNION ALL
            SELECT cs.claim_id, cs.supports_claim_id, d.depth + 1, cs.position
              FROM supports_cache.claim_supports cs
              JOIN downstream d ON cs.supports_claim_id = d.claim_id
             WHERE d.depth < ?{_EDGE_IS_ATTESTED}
        )
        SELECT DISTINCT claim_id, depth, position
          FROM downstream
         ORDER BY depth, position, claim_id
        """,
        (claim_id, depth),
    ).fetchall()
    return [dict(r) for r in rows]
