"""
scaffold.py — Creates and patches project directory structure and file templates.

All writes are idempotent: existing files are never overwritten unless force=True.
"""

from __future__ import annotations

from pathlib import Path
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Top-level project scaffold
# ---------------------------------------------------------------------------

GITIGNORE_TEMPLATE = """\
# mareforma — ignore processed outputs by default (large binary data)
data/*/processed/
.mareforma/artifacts/

# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
"""

PROJECT_TOML_TEMPLATE = """\
# mareforma.project.toml — project ontology
#
# This file is the human- and agent-readable record of your project's data
# sources.
#
# Add sources with:  mareforma add-source <name>
# Validate with:     mareforma check
# Inspect with:      mareforma explain [source]

[project]
name = "{name}"
description = ""
created = "{now}"
mareforma_version = "{version}"

[project.author]
name = "{author_name}"
email = "{author_email}"
institution = ""
"""

INIT_PY_TEMPLATE = """\
# {source_name}/preprocessing/__init__.py
# Generated by mareforma. Safe to extend.
"""

BUILD_TRANSFORM_TEMPLATE = """\
# {source_name}/preprocessing/build_transform.py
#
# Entry point for processing this data source.
# Use the @transform decorator to log each processing step.
# Call functions directly — there is no runner; you drive execution.
#
# Example
# -------
#   from mareforma import transform
#
#   @transform("{source_name}.normalize")
#   def normalize(input_path: str, output_path: str) -> None:
#       ...
#
#   if __name__ == "__main__":
#       normalize(
#           input_path="raw/",
#           output_path="processed/",
#       )
#
# Each @transform call appends a record to .mareforma/commits/transforms.jsonl.
# That file is your processing history. Commit it to git.
"""


def _write(path: Path, content: str, *, force: bool = False) -> bool:
    """Write *content* to *path*. Skip if file exists and force is False.

    Returns True if the file was written, False if skipped.
    """
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def scaffold_project(root: Path, project_name: str, version: str) -> list[str]:
    """Create the top-level mareforma project scaffold under *root*.

    Returns a list of human-readable messages describing what was created.
    """
    msgs: list[str] = []

    # Internal state directory
    commits_dir = root / ".mareforma" / "commits"
    commits_dir.mkdir(parents=True, exist_ok=True)
    msgs.append("  created  .mareforma/commits/")

    # Top-level dirs
    (root / "data").mkdir(exist_ok=True)
    msgs.append("  created  data/")

    # .gitignore
    gi = root / ".gitignore"
    if _write(gi, GITIGNORE_TEMPLATE):
        msgs.append("  created  .gitignore")
    else:
        msgs.append("  skipped  .gitignore (already exists)")

    # Project TOML
    from mareforma.git import get_user_config
    author = get_user_config()
    toml_path = root / "mareforma.project.toml"
    content = PROJECT_TOML_TEMPLATE.format(
        name=project_name,
        now=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        version=version,
        author_name=author.get("name", ""),
        author_email=author.get("email", ""),
    )
    if _write(toml_path, content):
        msgs.append("  created  mareforma.project.toml")
    else:
        msgs.append("  skipped  mareforma.project.toml (already exists)")

    return msgs


def scaffold_source(root: Path, source_name: str) -> list[str]:
    """Create the directory scaffold for a new data source under *root/data/*.

    Returns a list of human-readable messages describing what was created.
    """
    msgs: list[str] = []
    base = root / "data" / source_name

    for subdir in ["raw", "processed", "protocols", "preprocessing"]:
        d = base / subdir
        d.mkdir(parents=True, exist_ok=True)
        msgs.append(f"  created  data/{source_name}/{subdir}/")

    # preprocessing/__init__.py
    init_path = base / "preprocessing" / "__init__.py"
    if _write(init_path, INIT_PY_TEMPLATE.format(source_name=source_name)):
        msgs.append(f"  created  data/{source_name}/preprocessing/__init__.py")

    # preprocessing/build_transform.py
    bt_path = base / "preprocessing" / "build_transform.py"
    if _write(bt_path, BUILD_TRANSFORM_TEMPLATE.format(source_name=source_name)):
        msgs.append(f"  created  data/{source_name}/preprocessing/build_transform.py")

    return msgs
